# Created by Jekyll Writer
title: Old Tall's Blog
author: GH
description: This is a Jekyll blog site.
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: ghlogic123
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
