# Created by Jekyll Writer
title: Logic Rocks
author: Old Tall
description: 'Share some experience, notes and opinions here.'
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
github_username: ghlogic123
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
email: ghlogic123
